/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menu?: Array<
    | ({
        _key: string;
      } & PageReference)
    | {
        title?: string;
        url?: string;
        blank?: boolean;
        _type: "externalLink";
        _key: string;
      }
  >;
  slideshow_images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  socials?: Array<{
    title?: string;
    url?: string;
    _type: "externalLink";
    _key: string;
  }>;
  email?: string;
  phone?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ExperienceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "experience";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wip?: boolean;
  name?: string;
  slug?: Slug;
  introduction?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference?: PageReference | ExperienceReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              href?: string;
              blank?: boolean;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        asset?: SanityFileAssetReference;
        media?: unknown;
        title?: string;
        _type: "file";
        _key: string;
      }
  >;
  toc?: boolean;
  categories?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  email?: string;
  phone?: string;
  hours?: string;
  pricerange?: string;
  address?: string;
  location?: Geopoint;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wip?: boolean;
  contact_form?: boolean;
  name?: string;
  slug?: Slug;
  preamble?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference?: PageReference | ExperienceReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              href?: string;
              blank?: boolean;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | {
        asset?: SanityFileAssetReference;
        media?: unknown;
        title?: string;
        _type: "file";
        _key: string;
      }
  >;
  toc?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | PageReference
  | SanityImageAssetReference
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | ExperienceReference
  | SanityFileAssetReference
  | Experience
  | Geopoint
  | Page
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/lib/queries.ts
// Variable: tourismPageQuery
// Query: *[  _type == "experience"  && slug.current == $slug][0]{  ...,  "headings": content[style in ["h1", "h2", "h3", "h4", "h5", "h6"]],  content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,        "type": @.reference->_type,        "slug": @.reference->slug      }    },    _type == "image" => {      ...,      asset->    },    _type == "file" => {      ...,      asset->    }  }}
export type TourismPageQueryResult = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wip?: boolean;
  name?: string;
  slug?: Slug;
  introduction?: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href?: string;
              blank?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference?: ExperienceReference | PageReference;
              _type: "internalLink";
              _key: string;
              type: "experience" | "page" | null;
              slug: Slug | null;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          _type: "sanity.fileAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        title?: string;
        _type: "file";
        _key: string;
        markDefs: null;
      }
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  toc?: boolean;
  categories?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  email?: string;
  phone?: string;
  hours?: string;
  pricerange?: string;
  address?: string;
  location?: Geopoint;
  headings: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href?: string;
          blank?: boolean;
          _type: "externalLink";
          _key: string;
        }
      | {
          reference?: ExperienceReference | PageReference;
          _type: "internalLink";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: contentPageQuery
// Query: *[  _type == "page"  && slug.current == $slug][0]{  ...,  "headings": content[style in ["h1", "h2", "h3", "h4", "h5", "h6"]],  content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,        "type": @.reference->_type,        "slug": @.reference->slug      }    },    _type == "image" => {      ...,      asset->    },    _type == "file" => {      ...,      asset->    }  }}
export type ContentPageQueryResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wip?: boolean;
  contact_form?: boolean;
  name?: string;
  slug?: Slug;
  preamble?: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              href?: string;
              blank?: boolean;
              _type: "externalLink";
              _key: string;
            }
          | {
              reference?: ExperienceReference | PageReference;
              _type: "internalLink";
              _key: string;
              type: "experience" | "page" | null;
              slug: Slug | null;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          _type: "sanity.fileAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        title?: string;
        _type: "file";
        _key: string;
        markDefs: null;
      }
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  toc?: boolean;
  headings: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href?: string;
          blank?: boolean;
          _type: "externalLink";
          _key: string;
        }
      | {
          reference?: ExperienceReference | PageReference;
          _type: "internalLink";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: experiencePageQuery
// Query: *[  _type == "experience" && array::intersects(categories, $filters)][]{  ...,  image {    asset->{      ...,    }  }}
export type ExperiencePageQueryResult = Array<never>;

// Source: sanity/lib/queries.ts
// Variable: pageSlugsQuery
// Query: *[  _type == "page"  && defined(slug.current)  && coalesce(wip, false) == false][]{  "slug": slug.current,  _updatedAt}
export type PageSlugsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: experienceSlugsQuery
// Query: *[  _type == "experience"  && defined(slug.current)  && coalesce(wip, false) == false][]{  "slug": slug.current,  _updatedAt}
export type ExperienceSlugsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: layoutQuery
// Query: *[  _type == "settings" && _id == "settings"][0]{  ...,  menu[]{    ...,    _type == 'internalLink' => @->{slug, _id, name},    _type != 'internalLink' => @  }}
export type LayoutQueryResult = {
  _id: "settings";
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menu: Array<
    | {
        _key: string;
        _ref: string;
        _type: "reference";
        _weak?: boolean;
      }
    | {
        title?: string;
        url?: string;
        blank?: boolean;
        _type: "externalLink";
        _key: string;
      }
  > | null;
  slideshow_images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  socials?: Array<{
    title?: string;
    url?: string;
    _type: "externalLink";
    _key: string;
  }>;
  email?: string;
  phone?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: slideshowQuery
// Query: *[  _type == "settings" && _id == "settings"][0]{  slideshow_images[]{    ...,    asset->  }}
export type SlideshowQueryResult = {
  slideshow_images: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "experience"\n  && slug.current == $slug\n][0]{\n  ...,\n  "headings": content[style in ["h1", "h2", "h3", "h4", "h5", "h6"]],\n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        "type": @.reference->_type,\n        "slug": @.reference->slug\n      }\n    },\n    _type == "image" => {\n      ...,\n      asset->\n    },\n    _type == "file" => {\n      ...,\n      asset->\n    }\n  }\n}': TourismPageQueryResult;
    '*[\n  _type == "page"\n  && slug.current == $slug\n][0]{\n  ...,\n  "headings": content[style in ["h1", "h2", "h3", "h4", "h5", "h6"]],\n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        "type": @.reference->_type,\n        "slug": @.reference->slug\n      }\n    },\n    _type == "image" => {\n      ...,\n      asset->\n    },\n    _type == "file" => {\n      ...,\n      asset->\n    }\n  }\n}': ContentPageQueryResult;
    '*[\n  _type == "experience" && array::intersects(categories, $filters)\n][]{\n  ...,\n  image {\n    asset->{\n      ...,\n    }\n  }\n}': ExperiencePageQueryResult;
    '*[\n  _type == "page"\n  && defined(slug.current)\n  && coalesce(wip, false) == false\n][]{\n  "slug": slug.current,\n  _updatedAt\n}': PageSlugsQueryResult;
    '*[\n  _type == "experience"\n  && defined(slug.current)\n  && coalesce(wip, false) == false\n][]{\n  "slug": slug.current,\n  _updatedAt\n}': ExperienceSlugsQueryResult;
    "*[\n  _type == \"settings\" && _id == \"settings\"\n][0]{\n  ...,\n  menu[]{\n    ...,\n    _type == 'internalLink' => @->{slug, _id, name},\n    _type != 'internalLink' => @\n  }\n}": LayoutQueryResult;
    '*[\n  _type == "settings" && _id == "settings"\n][0]{\n  slideshow_images[]{\n    ...,\n    asset->\n  }\n}': SlideshowQueryResult;
  }
}
